import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import { ActionResponse } from "../types";

export const downloadComplaintDocx = async (data: ActionResponse) => {
  // Process the complaint text into paragraphs to preserve structure
  const complaintParagraphs = data.formalComplaint.split('\n').map((line) => {
    return new Paragraph({
      children: [
        new TextRun({ 
          text: line, 
          font: "Times New Roman", 
          size: 24 // 24 half-points = 12pt
        })
      ],
      spacing: { after: 120 }, // 120 twips ~= 6pt spacing
    });
  });

  const actionStepsParagraphs = data.actionSteps.map((step, index) => {
    return new Paragraph({
      children: [
        new TextRun({ 
          text: `${index + 1}. `, 
          bold: true, 
          font: "Arial", 
          size: 22 
        }),
        new TextRun({ 
          text: step, 
          font: "Arial", 
          size: 22 
        }),
      ],
      spacing: { after: 120 },
    });
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            text: "Formal Complaint Draft",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          
          // Meta Info: Category
          new Paragraph({
            children: [
              new TextRun({ text: "Category: ", bold: true, font: "Arial", size: 20 }),
              new TextRun({ text: data.classification, font: "Arial", size: 20 }),
            ],
            spacing: { after: 100 },
          }),
          
          // Meta Info: Authority
          new Paragraph({
            children: [
              new TextRun({ text: "Target Authority: ", bold: true, font: "Arial", size: 20 }),
              new TextRun({ text: data.recommendedAuthority, font: "Arial", size: 20 }),
            ],
            spacing: { after: 400 },
          }),

          // Visual Divider
          new Paragraph({
            text: "",
            border: {
              bottom: {
                color: "auto",
                space: 1,
                style: BorderStyle.SINGLE,
                size: 6,
              },
            },
            spacing: { after: 400 },
          }),

          // The Complaint Letter
          ...complaintParagraphs,

          new Paragraph({ text: "", spacing: { after: 400 } }),

          // Action Plan Header
          new Paragraph({
            text: "Recommended Action Plan",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 240 },
          }),

          // Action Steps
          ...actionStepsParagraphs,
          
          // Footer
          new Paragraph({
            children: [
                new TextRun({ 
                  text: "Generated by ComplaintAI", 
                  italics: true, 
                  size: 16, 
                  color: "808080" 
                })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 800 },
          }),
        ],
      },
    ],
  });

  // Generate and trigger download
  const blob = await Packer.toBlob(doc);
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `complaint_draft_${new Date().toISOString().split('T')[0]}.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};
