import { jsPDF } from "jspdf";
import { ActionResponse } from "../types";

export const downloadComplaintPDF = (data: ActionResponse) => {
  const doc = new jsPDF();
  const margin = 20;
  let cursorY = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxLineWidth = pageWidth - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Formal Complaint Draft", margin, cursorY);
  cursorY += 10;

  // Meta Info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by ComplaintAI`, margin, cursorY);
  doc.text(`Category: ${data.classification}`, margin, cursorY + 5);
  doc.text(`To: ${data.recommendedAuthority}`, margin, cursorY + 10);
  cursorY += 20;

  doc.setTextColor(0);
  doc.setDrawColor(200);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 10;

  // The Letter
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  
  const splitText = doc.splitTextToSize(data.formalComplaint, maxLineWidth);
  
  // Check if text fits, if not add page
  if (cursorY + splitText.length * 5 > doc.internal.pageSize.getHeight() - margin) {
     doc.addPage();
     cursorY = 20;
  }
  
  doc.text(splitText, margin, cursorY);
  
  // Calculate new Y position based on lines
  cursorY += splitText.length * 6 + 10;

  // Check page break for next section
  if (cursorY > doc.internal.pageSize.getHeight() - 60) {
    doc.addPage();
    cursorY = 20;
  }

  // Next Steps
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Recommended Action Plan", margin, cursorY);
  cursorY += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  data.actionSteps.forEach((step, index) => {
    const stepText = `${index + 1}. ${step}`;
    const splitStep = doc.splitTextToSize(stepText, maxLineWidth);
    doc.text(splitStep, margin, cursorY);
    cursorY += splitStep.length * 6;
  });

  doc.save("complaint_draft.pdf");
};
